### ISSUE TITLE
Please mention Modern Auth

### ISSUE THREAD

**Issue by oddhair** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1490]
We' keep running into orgs that buy the SRS v2 and then come to us asking if it supports Modern Auth. We were part  of the TAP for Rigel so I'm aware Modern Auth doesn't make sense for a system that reboots every day, but the planning and preparation documentation doesn't seem to mention Modern Auth at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Skype Room Systems v2 requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
@davgroom I can add a note on Modern Auth here if you approve.

**Comment by lindspea** [comment]
@jambirk @davgroom Just following up on this issue.  Has the note been added yet, or would you like me to do a PR?

**Comment by jambirk** [comment]
We need to hear from the PG first. @davgroom and @sohailta please respond to the OP's question about Modern Auth on Rigel.

**Comment by scanum** [comment]
@davgroom and @sohailta Any updates on this issue? Thanks.

**Comment by jambirk** [comment]
Adding @gregbari, this is something else to make mention of in a post-rebrand update. Please contact me off GH to see what we can do.

**Comment by sohailta** [comment]
We are looking at adding Modern authentication support for Microsoft Teams Rooms soon and are working on design for it. MFA is just one feature of the Modern auth. which would not make sense for room systems (As room systems reboot nightly, users in the rooms do not know the password, it is not operationally possible for IT admins to perform MFA across thousands of room using one or two phones and the fact that we don’t want log-in prompts appearing for users who can’t do anything about it). 
MFA also helps move to token based auth. which is critical to security on the wire so we are looking at Resource owner password credential grant mechanism (https://tools.ietf.org/html/rfc6749#section-4.3) to enable MA for Room systems. We will have more details as we finalize our design and get sign-off from security and will update our documentation per that.

**Comment by jambirk** [comment]
@sohailta  Since this question has come up a number of times, while other things are in process perhaps we should have an explicit statement in the planning articles. Please message me so we can discuss.

**Comment by scanum** [comment]
@oddhair - Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by PeteHaigh-MSFT** [comment]
Hi team why have we closed this off when this is still not mentioned in the documentation anywhere, and the Teams Rooms still don't support Modern Auth???
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39361102-do-not-require-legacy-auth-for-microsoft-teams-roo

**Comment by gregbari** [comment]
Good question.  Who closed it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
