### ISSUE TITLE
 Showing " [deploy-apps-microsoft-teams-landing-page.md] を参照･･･" (Markdown notation) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1894]
After #1816,  Showing " [deploy-apps-microsoft-teams-landing-page.md] を参照･･･" (Markdown notation) 

アプリ
アプリは、Teams (ファーストパーティ アプリ、または既定のアプリ) によって、またはサードパーティ (外部アプリ) によって提供される、タブ、コネクタ、ボットまたはそれらの 3 つを任意に組み合わせたのものです。[アプリ] の下で、既定のアプリを有効または無効にしたり、外部アプリを制御する設定を構成したりすることができます。Teams のアプリ、ボット、コネクタ、およびタブのロールアウトについては、(アプリ、ボット、およびコネクタ) [deploy-apps-microsoft-teams-landing-page.md] を参照してください。

https://docs.microsoft.com/ja-jp/microsoftteams/enable-features-office-365

**Comment by scanum** [comment]
@officedocsbot assign @officeglobal

**Comment by scanum** [comment]
@officeglobal Could you please take a look at this? Thanks!

**Comment by OfficeGlobal** [comment]
@scanum The broken link is a source issue, could you please update the source?
![image](https://user-images.githubusercontent.com/47977325/55215104-e8252b00-51f8-11e9-9f17-8803898c2146.png)

**Comment by OfficeGlobal** [comment]
Hello @LolaJacobsen, you're mentioned as author of the article. Could you please fix the reported link? 

**Current:** (Apps, bots, & connectors)[deploy-apps-microsoft-teams-landing-page.md]
**Expected:** [Apps, bots, & connectors](deploy-apps-microsoft-teams-landing-page.md)
**MD notation:**  \[Apps, bots, & connectors\]\(deploy-apps-microsoft-teams-landing-page.md\) 

Thank you

**Comment by scanum** [comment]
@LolaJacobsen Any updates on this? Thanks!

**Comment by Reeced40** [comment]
@OfficeGlobal please can you confirm if this issue has been sorted or which link/document you are referring to.

**Comment by OfficeGlobal** [comment]
**article:** enable-features-office-365.md
**author:** LolaJacobsen
**GH:** https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/enable-features-office-365.md
**live URL:** https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365

Once  fixed link in the source article the INTL will be updated too

![image](https://user-images.githubusercontent.com/47977325/59192242-1b355480-8b82-11e9-8959-dd6540c6df85.png)

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@OfficeGlobal Sorted out. Thank you.

**Comment by scanum** [comment]
@hyoshioka0128 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by hyoshioka0128** [comment]
en-us is fiexd, but ja-jp is not fixed.

en-us:https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365
![enable-features-office-365_e](https://user-images.githubusercontent.com/40815708/59960771-1e2c2f80-9508-11e9-8d87-c8056e976e66.png)

ja-jp:https://docs.microsoft.com/ja-jp/microsoftteams/enable-features-office-365
![enable-features-office-365_j](https://user-images.githubusercontent.com/40815708/59960772-24221080-9508-11e9-8fc2-562d2595da39.png)
