### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2549]
There is an invalid link in an article

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/microsoftteams/setting-up-your-phone-system?bc=/skypeforbusiness/breadcrumb/toc.json&toc=/skypeforbusiness/sfbotoc/toc.json
2. Search for "Set up a Cloud auto attendant"
3. Click on the link

**Actual results**:
Link does not work
**Expected results**:
Link should either work or be removed

**GH article**:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/setting-up-your-phone-system.md

![image](https://user-images.githubusercontent.com/47977325/60336016-857e2f80-999f-11e9-8547-1fc23de602ee.png)

**Comment by scanum** [comment]
@OfficeGlobal @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@OfficeGlobal Done.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by OfficeGlobal** [comment]
Hello,
Issue is still repro, could you please take a look at it ?
Thank you

**Comment by Reeced40** [comment]
@OfficeGlobal fixed thank you.
