### ISSUE TITLE
Missing issue: Unable to configure unanswered calls to go to voicemail when Exchange mailbox is on premises

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2620]
Feature area: Phone System
Issue title: Unable to configure unanswered calls to go to voicemail in the desktop app
Behavior / Symptom: When a user is in Teams-only mode, their Exchange mailbox is on premises and they access Settings &gt; Calls in the Teams desktop app, they cannot select the options to forward calls to voicemail (unanswered calls or all calls). If either option was already configured, the act of opening the Calls tab of Settings will disable forwarding to voicemail.
Known workaround: Configure forwarding to voicemail using the Teams mobile app.
Discovery date: 05/27/19
Reference: Office 365 ticket #14541129

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/known-issues)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@rgsteele Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@rgsteele I've created a PR and it will be live as soon as @LolaJacobsen will merge it

**Comment by rgsteele** [comment]
The issue with Teams appears to have been resolved now, so no need to update the doc.

**Comment by scanum** [comment]
@rgsteele Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by rgsteele** [comment]
The "Unable to configure unanswered calls to go to voicemail in the desktop app" issue is still listed in the Phone System section, despite the issue having been resolved back on July 24.
