### ISSUE TITLE
Installation context per user

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2868]
Why the MSI is now forced to run in user context? How are we supposed to do a machine wide install if it runs in user context?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by lindspea** [comment]
@LanaChin could you perhaps assist?

**Comment by baardhermansen** [comment]
@mrik23 The installer is a machine wide installer, in the sense that is installs for _every_ user that logs on the computer.  
Unfortunately, the installation needs to run pr. user, it's not sufficient with one installation to be valid for every user.
Every user get Teams installed to their %localappdata%\Microsoft\Teams folder.

**Comment by scanum** [comment]
@mrik23 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by TimTheITGuy** [comment]
I understood this issue was not resolved. Please indicate how we can install Teams once per machine to %programfiles% so that we do not have %localappdata% folders bloated with program files & executable(s)...

**Comment by baardhermansen** [comment]
@timtheitguy The machine wide installer is indeed installed only once per machine. However Teams needs to install for each individual user that logs on to the machine, and the default install folder is %localappdata%. You can change the install folder per user but it's not advised. 
Until Microsoft changes the way Teams work, there is no way to have one installation per machine, working for all users. 
Personally I'd like to have Teams installed like the majority of applications, into Program Files, but until that happens, individual user installations it is.

**Comment by JamesEdmonds89** [comment]
Please get this changed!
Trying to install Teams in an enterprise RDSH environment is a nightmare!

- We have users each with their own copy of Teams using space, bandwidth and time
- For some reason, for us Teams is installing ProgramData\%username%
- Getting this working with SRP is proving problematic
-  Users should not be able to run executables from their profiles
