### ISSUE TITLE
'Caller ID Policy' User Assignment Missing from Teams Admin Center UI

### ISSUE THREAD

**Issue by Chris8au** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3245]
[Enter feedback here]
Hi - As per the documentation "You can use the Microsoft Teams admin center to assign a custom policy to one or more users", however this ability is not in my Admin Center's UI.  

Under Voice>Caller ID Policy I can manage the Caller ID Policies fine but there is no reference to user assignments here.  Similarly, in the Users>Policies section, 8 Policies are visible - Caller ID is not one of them.

I can assign Caller ID Policies just fine with Powershell, and it works, so at a base level the feature is working - it's the Admin Center UI which is missing references to this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b8aefb-f373-fa6e-dd79-e97cded117e8
* Version Independent ID: 2c73f49c-d34f-c1da-648d-8675f10c0183
* Content: [Manage caller ID policies in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/caller-id-policies)
* Content Source: [Teams/caller-id-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/caller-id-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Chris8au Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Chris8au Thank you for reaching out.  Please let me know if this article helps. https://docs.microsoft.com/MicrosoftTeams/teams-policies

**Comment by Chris8au** [comment]
@lindspea Hi Lindsay, thanks for link!

The linked article advises that Caller ID policies can be applied to users via the Teams Admin Center, but in my Admin Center I don't have this ability,  I cannot apply Caller ID policies to specific users in the Teams Admin Center, I can only do this via Powershell.  

I understand that this feature is still being rolled out so I guess my question here is, is the ability to apply Caller ID policies to specific users via the Teams Admin Center still coming, is it meant to be there already, or is the document inaccurate and this is will only be a Powershell thing?

Thank you!

Chris

**Comment by lindspea** [comment]
@Chris8au I'll double check with the team and get back to you soonest.

**Comment by lindspea** [comment]
@Chris8au Hi there. I checked with the team and the feature is still in the pipeline, so not yet released.

**Comment by scanum** [comment]
@Chris8au Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by dinocaputo** [comment]
This is still an issue.  The following does NOT work in the Teams Admin Center
Assign a custom calling line ID policy to multiple users at a time
To assign a custom calling line Id policy to multiple users at a time, see Edit Teams user settings in bulk.

Or, you can also do the following:

Go to Microsoft Teams admin center > Voice > Caller ID policies.
Select the policy by clicking to the left of the policy name.
Select Manage users.
In the Manage users pane, search for the user by display name or by user name, select the name, and then select Add. Repeat this step for each user that you want to add.
When you're finished adding users, select Save.

**Comment by gabororsi** [comment]
The Manage Users option still not visible.
