### ISSUE TITLE
TLS version for SFB Edge 2019 on Win2019

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3258]
the security note in this article says "Security note: To ensure the strongest cryptographic protocol is used, Skype for Business Server 2019 will offer TLS encryption protocols in the following order to clients: TLS 1.3, TLS 1.2. TLS is a critical aspect of Skype for Business Server 2019 and thus it is required in order to maintain a supported environment."

I have SFB 2019 Edge server deployed on Win2019. When I run TLS checks for Access Edge public IP on port 443 (for client SIP/TLS), the https://www.ssllabs.com/ssltest/ tool shows SFB 2019 Edge server supports the following TLS versions:
TLS 1.3	No
TLS 1.2	Yes
TLS 1.1	Yes
TLS 1.0	Yes
SSL 3	No
SSL 2	No

So, TLS 1.3 is not supported and TLS 1.0 and TLS 1.1 are supported!?!?

Does it mean the documentation is incorrect? Or it is only applicable to HTTPS traffic? Or only applicable to internal SFB servers such as Front Ends?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7679160-fb98-6e52-07f3-b844ba979065
* Version Independent ID: a137b9d1-7721-c4ba-b2bd-0122795e80b6
* Content: [Encryption for Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/security/encryption)
* Content Source: [Skype/SfbServer/plan-your-deployment/security/encryption.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/security/encryption.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@shivtorov  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @LanaChin @MicrosoftHeidi I see that 1.3 was added to the article not so long, can you please confirm if SfB 2019 supports TLS 1.3? could not find another official statement and I could repro what @shivtorov is saying here. Thank you

**Comment by get-itips** [comment]
Hello @LanaChin @MicrosoftHeidi did you have chance to review my comments? thanks in advance

**Comment by shivtorov** [comment]
@scanum , I have just noticed that all doc pages for on-premises SFB Server don't show GitHub integration any more. Including the question raised in this github issue is not shown on the content page.

Has it been done on-purpose or simply something is broken? 
Does it mean Microsoft will not update SFB Server 2019 documentation any more?

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
Regarding this- We are investigating at the moment.

@scanum , I have just noticed that all doc pages for on-premises SFB Server don't show GitHub integration any more. Including the question raised in this github issue is not shown on the content page.Has it been done on-purpose or simply something is broken?Does it mean Microsoft will not update SFB Server 2019 documentation any more?
--

**Comment by shivtorov** [comment]
> @shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
> Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@scanum, there were no changes to the status of this issue with documentation. The information in the article still does not meet the reality. @get-itips has confirmed above that it is indeed the case. Either the article is providing false info about TLS versions supported by SFB Server 2019, or it is missing a note that some manual configuration steps are required to achieve the TLS settings described in the article.
