### ISSUE TITLE
Private Channels setting

### ISSUE THREAD

**Issue by dseehof** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3279]
The setting is there in the policy, but I wouldn't know where to actually create one in the app.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd13cd2b-3dca-1b7c-9970-c0f8c2348712
* Version Independent ID: 318c6208-531a-3600-e45b-c43ea845db86
* Content: [Manage teams policies in Microsoft Teams](https://docs.microsoft.com/en-gb/MicrosoftTeams/teams-policies#feedback)
* Content Source: [Teams/teams-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by mkiah** [comment]
I'm seeing the same problem here.

## Expected Behavior
Option to create a private channel

## Actual Behavior
There is no option to create a private channel

## Steps to Reproduce the Problem

  1. Select the options dropdown next to an existing Team
![image](https://user-images.githubusercontent.com/46502806/67696516-45868380-f964-11e9-9912-4046f9363a9f.png)

  1. Choose "Add channel"
  1. No option to create as a private channel:
![image](https://user-images.githubusercontent.com/46502806/67696673-841c3e00-f964-11e9-933a-5645f7adcb5f.png)

Note, this option is also missing from the "Manage channel" option on existing channels:
![image](https://user-images.githubusercontent.com/46502806/67696736-9f874900-f964-11e9-81b7-552661cbaf5c.png)


## Specifications

  - Version: 1.2.00.26774
  - Platform: Windows 10 Enterprise
  - Subsystem: version 1809, OS build 17763.737

**Comment by scanum** [comment]
@dseehof  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @dseehof and @mkiah, thank you for your feedback.

You have to wait until November for this feature:
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=50588

**Comment by kaosaxis** [comment]
I just received an email this has been rolled out. I too am not seeing the changes.

**Comment by kaosaxis** [comment]
You have Microsoft Teams Version 1.2.00.27559 (64-bit). It was last updated on 10/27/19.
I'm even running the developer preview version.

**Comment by dariomws306** [comment]
It should be available soon, they started rolling out the feature for all tenants this week:
https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-New-in-Microsoft-Teams-Ignite-2019/ba-p/937025

**Comment by scanum** [comment]
@dseehof 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by tang1397** [comment]
I still have this issue on my Teams.  Do not see the Privacy choice to create a private channel.
