### ISSUE TITLE
Limited Firefox support

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3286]
The article states browsers supported but Firefox has only limited support. 

For example when one clicks the "**Reply in Teams**" link in the standardized "Y**our teammates are trying to reach you**" email messages Teams sends out when your default browser is Firefox. In this case the ‘**Join on the web instead**’ button is missing and in some cases Teams is actively promoting the use of Edge with a "**Join in Microsoft Edge**" button.

I find it highly disturbing that Microsoft purposely limits web functionality for Teams in Firefox and tries to dictate companies which browser they should use.

Either fix the article with this limitation or better yet fix the product and facilitate the use of all major browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@SjoerdV  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @SjoerdV, thank you for your feedback.

I think it's there:
"Meetings are supported only if the meeting includes PSTN coordinates. To attend a meeting on Firefox without PSTN coordinates, users must download the Teams desktop client."

**Comment by SjoerdV** [comment]
I am sorry but this has nothing to do with Meeting functionality. The link is received through email when someone does not have Teams 'open' and someone has mentioned him/her (Subject of the email is: "You have new messages in Teams"). The link presented is to a chat/conversation, not to a meeting. Just because the intermittent webpage is the same for a link to a meeting as it is for a link to a chat/conversation, does not mean it should behave the same in Firefox as Firefox is perfectly capable of displaying a chat/conversation when the entry point is the teams.microsoft.com url, helas it is not so when using the direct link in the email. So there you see there exists a totally different scenario where Firefox can not be used and thus contributes to a limited support scenario.

**Comment by jeffvandyke** [comment]
Same issue, same use-case - opening a teams link (conversation) from an email - link looks like this: `https://teams.microsoft.com/dl/launcher/launcher.html?url=%2f_%23%2fl%2fchat%2f19%3a<some-anonymized-long-hash>%40thread.v2%2fconversations%3ftenantId%3d<some-anonymized-guid>%26lm%3ddeeplink%26lmsrc%3demail%26emltid%3d<some-anonymized-guid>%26linkpos%3d3%26emltype%3dNew_Activities%26linktype%3dopenSkypeTeams%26cmpid%3dmissedActivity&type=chat&deeplinkId=<some-anonymized-guid>&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true`. When I open teams in Firefox, it works great.

I have to re-emphasize: Firefox's health and support is critical to the diversity of the web, and a diverse web ecosystem is absolutely necessary in order to keep Google (in this case as Chromium's maintainer) accountable to a standards process to ensure new features to the web platform are properly reviewed and well designed, as opposed to Chrome going off in its own broken direction like Internet Explorer was known to do. This is also corroborated by CSS-Tricks in the article ["Browser Diversity Commentary, Regarding the Edge News"](https://css-tricks.com/browser-diversity-commentary-regarding-the-edge-news/).

**Comment by scanum** [comment]
@SjoerdV 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jeffvandyke** [comment]
Just tried this - still broken, still recommending "For the best meeting experience, open the link in Google Chrome" from a link opened from email...

**Comment by jeffvandyke** [comment]
I've also got a better link template that causes this issue - the original one, not what I posted before which was a redirection resolution:  `https://teams.microsoft.com/l/chat/<2-digits>:<anonymized-guid>_<other-guid>@unq.gbl.spaces/conversations?tenantId=<anonymized-tenant-guid>&data=01|01|jeff@anonymized-email.com|<anonymized-guid>|<anonymized-other-guid>|0&sdata=<long-ish-base64-string>2M=&reserved=0`

**Comment by SjoerdV** [comment]
@scanum I think the statements of @jeffvandyke in his first post were a little confusing "Same issue, same use-case" and "When I open teams in Firefox, it works great.", but I think he meant to say there is still that problem as per his posts after you closed it. I also concur: the links still do not open in Firefox 'on the web', so please reopen the issue as it has not been solved OR the article is not amended with additional exception notices for Firefox in the Browser table.

**Comment by dariomws306** [comment]
Hi @SjoerdV and @jeffvandyke, thank you for your comments.

To provide feedback about an issue you should open a support case:
https://docs.microsoft.com/office365/admin/contact-support-for-business-products

To request features you should go to:
https://microsoftteams.uservoice.com/
I think there is a similar request so you can add a vote:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38632123-links-to-channels-open-web-app-in-firefox-and-ch

We are here to help with docs improvement. In this article we have two columns about limitations: "Calling - audio, video, and sharing" and "Meetings - audio, video, and sharing". So I think I cannot add this limitation to one of them, maybe a note.

@LolaJacobsen What do you think?

Thanks!

**Comment by SjoerdV** [comment]
I would just add a limitation to the article called: “Conversation / Channel URL links - originating from automated Teams email notifications”
