### ISSUE TITLE
NER formula is wrong

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3384]
the formula given is missing the divided by total calls for percentage value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf8b00d-17dc-7655-abc6-34ef14f00ecc
* Version Independent ID: 08606d75-3213-6a5c-ebc4-6b902bff86df
* Content: [Health Dashboard for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-health-dashboard#feedback)
* Content Source: [Teams/direct-routing-health-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-health-dashboard.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by RahulDube** [comment]
https://en.wikipedia.org/wiki/Network_Effectiveness_Ratio

Above article can help to get correct formula.
Ref:  ITU-T Recommendation E.425

**Comment by lindspea** [comment]
@TheBluLion thank you for reaching out and helping improve MS Docs. It seems the article has been fixed in the interim. Please confirm.

**Comment by TheBluLion** [comment]
No, it looks like the line NER = Answered calls + User Busy + Ring no Answer + Terminal Reject Seizures x 100 is still missing the divided by total calls.

**Comment by lindspea** [comment]
@CarolynRowe please have a look and let me know if this should be added to the article.

**Comment by CarolynRowe** [comment]
Merged PR this morning to address this issue.  Closing...
