### ISSUE TITLE
I don't have this ability on my Teams setup

### ISSUE THREAD

**Issue by Mexicoder** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3492]
i can't find the private team Discoverable configuration in my teams setup. why could that be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5920152-5fee-41ed-56df-ad7b51b25cc2
* Version Independent ID: 88cfc850-5e36-48ee-ba99-088b2b653f1e
* Content: [Manage discovery of private teams in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams#feedback)
* Content Source: [Teams/manage-discovery-of-private-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-discovery-of-private-teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@medhatelmasry Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by chetgandhi** [comment]
We dont have this as well.

**Comment by avogadro23** [comment]
This is also not available for my team.
@scanum It's been two weeks, what have you learned?

**Comment by RipRapRob** [comment]
Not available here either, one week later.

**Comment by mymebenha** [comment]
I don't have this option when creating a team and the option is also missing from the team settings section.  How do we get this functionality?

**Comment by Naz9mm** [comment]
Is this related to this setting Org wide Settings>Teams Settings> Search by Name - Scope Directory Search using an exchange address book policy.  Try it with this Off

**Comment by Mexicoder** [comment]
> @medhatelmasry Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

Are there any updates on this?

**Comment by iks170** [comment]
I am experiencing the same issue. Did anyone find a solution to this?

**Comment by sowjanya365** [comment]
Hi @Mexicoder 

Thank you for submitting feedback. I think the best way forward is if you open a service ticket in your tenant so this can get addressed ASAP. Based on the outcome let me know if it is something that can
be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Thank you!

**Comment by scanum** [comment]
@Mexicoder Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by RipRapRob** [comment]
How can you close this without confirmation that it has been solved?

FYI: I still don't have this setting (just tested it on private Team I just created and 'old' Teams).

**Comment by Mexicoder** [comment]
@scanum I still don't see any change. 
I am asking this issue to get reopening because I am not the only user that is being affected by this and because I am not able to reopen the issue myself.

As for improvement to the documentation, I can't suggest anything short of removing the public claim this feature exists when there are clearly people in the community experiencing this issue as well.
I not suggesting this however b/c that is an extreme ask.

I do hope to hear about this getting resolved soon or documentation updates as to how to enable this feature.
