### ISSUE TITLE
Badly formatted table

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3692]
All tables on this page are badly formatted. The columns aren't properly aligned and it doesn't make sense to have column headers for nearly every row. The page should be redesigned so it's easy to read it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ddf8ce-fda9-ee9d-d96a-801f9a2f66b7
* Version Independent ID: 9aa5a49f-c440-95a8-83a1-9d38bdaeda39
* Content: [Known issues for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/known-issues#linux)
* Content Source: [Teams/Known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Known-issues.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@GiantCrocodile Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@GiantCrocodile Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by GiantCrocodile** [comment]
This issue is not fixed @scanum. See the pull request which @dariomws306 did create. There are open questions and the changes weren't merged.
