### ISSUE TITLE
Dialin numbers for Teams conferences

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4548]
I ended up on this page. I don't have phone numbers assigned to users, I'm just looking for a local dialin number. Teams consistently gives me a San Diego number, and I'm based in Los Angeles. I can't seem to fix this. This page doesn't tell me how, exactly.

This is not a service request issue - it's a documentation issue. There are several critical things this page doesn't address.

1) How to get additional toll numbers for dialin users. You don't cover all countries; Monaco, for example, isn't listed.

2) What costs are involved if you "place an order". 

3) What happens if you have advanced conferencing, and not voice. 
All I wanted was a dialin number that's local for some of my external users that are attending my conferences. This page implies it's for this purpose, but seems to be left out. 

So fine, I figured I'd just request a toll free number for Monaco. I was worried I'd have to pay for it, but let's go for it. So then I get an error: "We can't do this because Communication Credits haven't been set up. "   

4) This page doesn't address Communication Credits; if it's a prerequisite, it should be mentioned somewhere on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e37f13b-cb86-955e-147c-fa916da063f9
* Version Independent ID: 4dd77188-abcb-fae2-3cf3-12b82b591bad
* Content: [Getting phone numbers for your users - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/getting-phone-numbers-for-your-users#get-new-phone-numbers-for-your-users)
* Content Source: [Teams/getting-phone-numbers-for-your-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/getting-phone-numbers-for-your-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jgwinner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jgwinner, thank you for your feedback.

This article is to assign phone numbers to users. If you want a phone number to call into a meeting, please check this article:
https://docs.microsoft.com/microsoftteams/set-up-audio-conferencing-in-teams

**Comment by scanum** [comment]
@jgwinner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jgwinner** [comment]
How is the situation resolved? My numbers are still San Diego, this document still pops up on search, the linked documentation still doesn't tell you how to change numbers, and everything is "open a service request?"

Why is something that is so essential and should be simple, turn into a service request?

Do you guys get payment from long distance calls and are attempting to obfusticate this via tech support?

**Comment by dariomws** [comment]
Hi @jgwinner,

My apologies if the article I sent you no helps. I think the article has all the steps to acquire services numbers for Audio Conferencing.

If the numbers you acquired does not service numbers you won´t be available to assign them for Audio Conferencing. I think you should remove them and acquire new numbers.
But I cannot help you here, please, you need to open a support ticket to get more assistance.
