### ISSUE TITLE
Removing members not possible with Azure AD Connect

### ISSUE THREAD

**Issue by desmondgc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4914]
Please clarify: "Even though members can't leave an org-wide team, as a team owner, you can manage the team roster by removing accounts that don't belong." In our environment, manually-removed members they are re-added several hours later. Is this expected behavior with Azure AD Connect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76309c0b-2a9c-36a8-d7c7-f7d6f311d39b
* Version Independent ID: bc69c0e3-0fa7-c86e-5e8c-067c8811e9bf
* Content: [Create an org-wide team in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/create-an-org-wide-team)
* Content Source: [Teams/create-an-org-wide-team.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/create-an-org-wide-team.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@desmondgc  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@desmondgc thank you for reaching out and helping improve MS Docs. I see this article has recently been updated. There is also information mentioning the following in the article - "Make sure you use Teams to remove users from your org-wide team. If you use another way to remove a user, such as the Microsoft 365 admin center or from a group in Outlook, the user might be added back to the org-wide team." Please let me know if you need further assistance.

**Comment by desmondgc** [comment]
Indeed, I saw this guidance and used Teams to remove users from my org-wide team. Nonetheless, the users we re-added several hours later.

**Comment by lindspea** [comment]
@desmondgc thank you for clearing that up. I'll chat to the team and get back to you soonest.

**Comment by scanum** [comment]
@desmondgc  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by desmondgc** [comment]
I'm not sure why this was closed. It is most definitely not resolved.

The documentation is misleading. It implies that there is a way to remove members from an org-wide team, but that is not the case in our environment. I suspect it's related to Azure AD Connect but have no way to verify this suspicion.

Consider adding a note to the "Remove accounts that might not belong" section that it might not be possible to remove accounts in certain environments.
