### ISSUE TITLE
Recovery tool does not work on Windows 109 Version 1909

### ISSUE THREAD

**Issue by danieldhudson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5201]
Just tried to use the tool on a Lenovo ThinkSmart Hub 500 running Windows version 10.0.18363 and the tool says it's not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13376c1b-df70-83de-8e6a-8ddc940774b5
* Version Independent ID: 6a2531ee-ac88-ee83-b858-1928d6cb4c65
* Content: [Use the Microsoft Teams Rooms recovery tool - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/rooms/recovery-tool)
* Content Source: [Teams/rooms/recovery-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/recovery-tool.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@danieldhudson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by danieldhudson** [comment]
I’ve had a look into it. The RecoveryTool.ps1 only validates up to Windows 10 1903 (18362 - still referred to as 19H1 in the script). I added a new validation variable on my copy to include 1909 (18363) and it validated and ran. I can also confirm that it seemed to work for me on a Lenovo ThinkSmart Hub 500 and I successfully rebuilt on 1909.

**Comment by scanum** [comment]
@danieldhudson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by danieldhudson** [comment]
Issue is not resolved. I have worked around the issue but the core issue still remains that the Recovery Tool does not work out of the box with Windows 10 1909
