### ISSUE TITLE
Could you please correct the title?

### ISSUE THREAD

**Issue by hideokamine** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5489]
[フィードバックをこちらに入力してください]
このページのタイトルは ”Microsoft Teams でユーザーにライセンスを割り当てる” ですが、正しくは ”Microsoft Teams でユーザーにポリシーを割り当てる” ではないでしょうか。

英語ページでは、 ”Assign policies to your users in Microsoft Teams” となっています。

The title of this page is "Microsoft Teams でユーザーにライセンスを割り当てる”, but I think the correct title is "Microsoft Teams でユーザーにポリシーを割り当てる".

On the same page in English, It is displayed "Assign policies to your users in Microsoft Teams".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Microsoft Teams でユーザーにライセンスを割り当てる - Microsoft Teams](https://docs.microsoft.com/ja-jp/MicrosoftTeams/assign-policies)
* Content Source: [Teams/assign-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@officeglobal Could you kindly help on this issue? Thanks!

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hideokamine , @scanum article was HumanTranslated and published live. The title was fixed

**Comment by hideokamine** [comment]
![image](https://user-images.githubusercontent.com/48910425/90779697-18fb8800-e339-11ea-82bf-748edd144798.png)

@OfficeGlobal Thank you! but, The title isn't fully fixed yet...

**Comment by OfficeGlobal** [comment]
@hideokamine We've updated the text in left navigation as well
![image](https://user-images.githubusercontent.com/47977325/91127674-04a3ec00-e6a7-11ea-8193-54e80163f26f.png)

**Comment by hideokamine** [comment]
@OfficeGlobal Thanks a lot.

**Comment by scanum** [comment]
@hideokamine  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
