### ISSUE TITLE
Not clear details 

### ISSUE THREAD

**Issue by vT15** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5554]
“ 4,6, or 8 It's important to understand the underlying non-uniform memory access (NUMA) configuration and configure your VM”

4,6 or 8 vCPU is it per user ? I need value per user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@vT15  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by vT15** [comment]
Unfortunately it’s not resolved yet and information on website is not
clear to me

**Comment by Reeced40** [comment]
@vT15 Thank you for reaching out. It looks like the document has been updated. Please let me know if you still haven't found your answer.

**Comment by scanum** [comment]
@vT15  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
