### ISSUE TITLE
Each user in your organization must have a Teams license before they can use Teams.

### ISSUE THREAD

**Issue by jaspreetjolly** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5561]
Article mentioned "Each user in your organization must have a Teams license before they can use Teams". However for joining Teams meetings, no licenses are required Refer: https://docs.microsoft.com/en-us/MicrosoftTeams/quick-start-meetings-live-events#get-licenses-for-meetings-and-live-events. 
We should have an * marked next to this mentioning "for meetings refer the meetings article."

**Comment by scanum** [comment]
@jaspreetjolly  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jaspreetjolly** [comment]
Hi Manuela, the issue with document is still there. Here is the latest screenshot which still shows "Each user in your organization must have a Teams license before they can use Teams"

![Annotation 2020-08-20 160747](https://user-images.githubusercontent.com/47853237/90760346-58a57e00-e2ff-11ea-8c38-7d4ac7647460.jpg)
