### ISSUE TITLE
Conflicting information about Stream licensing and permissions X ability to Record 

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5575]
The content under https://docs.microsoft.com/en-US/microsoftteams/cloud-recording#make-sure-users-have-upload-video-permissions-in-microsoft-stream  Section contradicts footnote 1 in https://docs.microsoft.com/en-US/microsoftteams/cloud-recording#prerequisites-for-teams-cloud-meeting-recording section.

**The users who are in this restricted list will not be able to record 
X
 1 Important

**Users won't need a Microsoft Stream license assigned if you want users to only record** and download the recordings.

The first statement is false and will cause confusion and frustration as admin may think that by restricting users to create content on Stream it would prevent the users from recording meetings.

Please revise and rewrite.

Thanks!

Jorge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@JorgeALeitao  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by JorgeALeitao** [comment]
I'm sorry but I beg to differ.
The paragraph states
"For a Teams user's meetings to be recorded, Microsoft Stream must be enabled for the tenant. In addition, **the following prerequisites are required** for both the meeting organizer and the person who is initiating the recording:

User has Office 365 E1, E3, E5, A1, A3, A5, M365 Business Premium, M365 Business Standard, or M365 Business Basic.
_**User needs to be licensed for Microsoft Stream1
User has Microsoft Stream upload video permissions**_

That's not true as the recording will happen if either of both conditions aren't fulfilled and this will lead customer's admins in error. 

That condition is true to jut to upload the recording to Stream once AMS makes is available.

**Comment by tonysmit** [comment]
@SamChung-MS - here is another thread on Cloud Recording.

**Comment by tonysmit** [comment]
@JorgeALeitao - I'm coming in to this way late, but has this been resolved yet. @SamChung-MS made a ton of edits to this document that I just merged. Please take a look at it and see if the problem still exists. If it does please let me know. Thanks, Tony

**Comment by SamChung-MS** [comment]
There was an error in: https://docs.microsoft.com/en-US/microsoftteams/cloud-recording#make-sure-users-have-upload-video-permissions-in-microsoft-stream

In that page it states that users in the restricted list within Stream will not be able to record. This isn't true. They'll still be able to record, it's just that their recordings won't be saved to Stream, and will instead be saved to ASM for 21 days.
I've submitted a PR to have that page updated.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SamChung-MS** [comment]
ah man. totally correct. That line of text is still wrong. Thank you for the call out. I've submitted another PR to get that page updated.
