### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5578]
This is incorrect: in the Microsoft Teams admin center, go to Meetings > Conference bridges. 

There is no Conference bridges option under Meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6e2b61-656c-a4f8-94a7-ec3c14e4d65e
* Version Independent ID: 77932de0-0312-95c5-f356-89ece9b3aabd
* Content: [Phone numbers for Audio Conferencing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/phone-numbers-for-audio-conferencing-in-teams)
* Content Source: [Teams/phone-numbers-for-audio-conferencing-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-numbers-for-audio-conferencing-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@SeaGT  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Reeced40** [comment]
@SeaGT Thank you for your feedback. If this issue has been resolved, please let me know. Otherwise, let me know what's reflecting on your side. Thanks.

**Comment by SeaGT** [comment]
Hi there,

Thanks for reaching out but this issue is still not resolved.  Your document (dated 6/9/2020) still states:

But in my Teams Admin Center, there is still not an option for Conference Bridges:

Cheers

Greg                                      

gregt@preceptwine.com    Tacoma 9/28-10/1

Desk: 206.576.6012 | IT Support: 206.576.6013

**Comment by scanum** [comment]
@Reeced40 Could you please look into this? Thanks!

**Comment by Reeced40** [comment]
@tonysmit Hi Tony, please could you assist. Any idea why the prompt is not reflecting on @SeaGT side?

**Comment by tonysmit** [comment]
@SeaGT - Hello. Sorry, I'm really late to this. Has this been resolved? There is really only 1 reason for it to not be showing in the nav and that's licensing. However, that said, on 10/1/2020 we released free Audio Conferencing so it should be showing. This offer is only available to new orgs/orgs that never had Audio Conferencing in the past. Meaning, you haven't bought any AC licenses including in an E5 license. Reply here again if it's not resolved. Thanks.

**Comment by scanum** [comment]
@SeaGT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
