### ISSUE TITLE
Blur needs support of AVX and not AVX2

### ISSUE THREAD

**Issue by HolgerJeromin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6401]
According to 
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40115269-blur-option-disappeared
Teams added support for AVX for background in June 2020.
But the documentation still states otherwise.

> Background video effects require Windows 10 or a processor with AVX2 instruction set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a61ff5-b3a5-158d-149a-dec344060e05
* Version Independent ID: 97fac351-a283-aaa8-cde1-fbd9cf4e8504
* Content: [Hardware requirements for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-requirements-for-the-teams-app)
* Content Source: [Teams/hardware-requirements-for-the-teams-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-requirements-for-the-teams-app.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@HolgerJeromin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by HolgerJeromin** [comment]
> We understand that this issue has been resolved.

Has it?
The current version (dated 03/05/2021) has still the same sentence in it:
> Background video effects require Windows 10 or a processor with AVX2 instruction set.

**Comment by dariomws** [comment]
@HolgerJeromin AVX works ONLY if you're running Windows 10. If you're not on Windows 10, you still need AVX2.
