### ISSUE TITLE
Missing terms definition

### ISSUE THREAD

**Issue by mtrudel-e3k** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7767]
What does these mean ?
The reports are useless without know what the codes mean
CUstomers asking what does it mean
their guess is as good as mine

Call Queue Target Type :
User ??? what does this mean

Call Queue Call Result:
Timed_out
transfered_to_agent  (did the agent actually took the call ?) who knows ?

overflown ? Hein what does this mean
disconnected ? in what circompstances does this happens

on another field I saw "other"  what could it possibly be ?

My customers are regretting their move to Teams Voice because of lack of reports ... that they all had with their old system
Not recommendind Teams Voice anymore unless the customer does not care about reports

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628345c6-f5f9-fe8e-bfff-faea00a8a25c
* Version Independent ID: 30f2d051-5af5-0063-7099-38b5b08ec1e4
* Content: [Auto Attendant & Call Queue Historical Report - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/aa-cq-cqd-historical-reports)
* Content Source: [Teams/aa-cq-cqd-historical-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/aa-cq-cqd-historical-reports.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@CLYVR can you take a look?

**Comment by mtrudel-e3k** [comment]
Hello Mike. Thanks for the quick response.
What exactly do you want me to look at. I reviewed the page and it looks the same to me.

**Comment by CLYVR** [comment]
Hi @mtrudel-e3k 

Happy to have a call with you to discuss in more detail.

The result values all relate to how the Call Queue has been configured by the Administrator.

**Call Queue Call Result text Call queue call final state:**

- Agent Joined Conference - the Call Queue is configured to use "Conference mode" and an agent joined the conference (ie. the call was answered by the agent).
- Disconnected - the caller abandoned (hung up before being answered by an agent)
- Error, failed, invalid - some error has occured
- Transferred To Agent - the Call Queue is configured to use transfer mode (or more specifically is not configured to use "Conference mode") and the call was transferred to the agent (ie. answered by the agent).
- Overflown - a call is overflow when the maximum number of calls as configured on the Call Queue "Call overflow handling" section is reached.
- Timed Out - a call times out when it has waiting the amount of time as configured on the Call Queue "Call timeout handling" section.

**Call Queue Target Type text Call redirection target type:**

Redirection targets only apply for Overflow and Timeout calls - that is when calls are "redirected" away from the Call Queue.

- ApplicationEndpoint - the redirection target is set to Voice App (ie. another Auto Attendant or Call Queue)
- Mailbox - the redirection target is shared voicemail
- Other - the redirection target is external phone number
- User - the redirection target is person in the organization


Hope this helps.

Colin

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
@scanum - a PR has not been created yet for this issue. Thanks.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mtrudel-e3k** [comment]
Thanks Johan
Yes the information you provided was VERY helpful

**Comment by nwoycik** [comment]
Hi,

Thanks a lot for this part of the missing terms definition, but I am still missing the following ones from the:
AACallFlow	Text	Encapsulates the different states of Auto Attendant Call -- possible values:

§ abs_search: ?

§ announcement:

§ automatic_menu:

§ call_termination:

§ call_transfer:

§ first_level_menu:

§ main_menu:

§ speech_input_confirmation:

§ user_selection:

I would need to correlate with what appears in the CQ figures, in order to clarify how many real calls were correctly attended, transfered to another AA or CQ, and mainly, the difference between first_level_menu and main_menu.

Thanks a lot....

**Comment by CLYVR** [comment]
Hi @nwoycik 

The AACallFlow field reports on the various stages of a call as it makes its way through an auto attendant.  Depening on your AA configuration you may not see all of the values show.  Here, at a high level, is what they mean:

§ abs_search:  - directory search - dial by name 
§ announcement: - an announcement was played via the AA menu option Announcement feature
§ automatic_menu: - unknown - I will look into this one further
§ call_termination: AA terminated the call - see AACallResult for more information
§ call_transfer: AA transferred the call - see AACallResult and AATransferAction for more information
§ first_level_menu: Menu option is enabled and menu was played
§ main_menu: call entered the AA / was returned to the start of the AA (ex. from an announcement)
§ speech_input_confirmation: - unknown - I will look into this one further
§ user_selection:  directory search - dial by name - when a user from a list is selected (believe this is the case - waiting for data confirmation)

**Comment by nwoycik** [comment]
Hi Colin,

Great información provided.  Me and my customer thank you a lot!!!.  Realky Apreciate your promptt and quick answer.

BEST regards!!!


Writing from mobile API.




Nicolás Woycik
UCC technical arquitect

***@***.***


Emilio Vargas, 12-14
28043 Madrid - España / +34 93 304 32 22
 / +34912961385


seidor.es<http://www.seidor.es>


***@***.***<https://twitter.com/seidor> ***@***.*** <https://www.linkedin.com/company/39568/>


***@***.***         Antes de imprimir este mensaje, asegúrese de que sea imprescindible. Proteger el medio ambiente está a nuestro alcance.


La información que contiene este correo electrónico es confidencial y compete exclusivamente al destinatario. Si Vd ha recibido esta comunicación por error, por favor, notifíquelo inmediatamente al remitente y borre el mensaje junto con sus ficheros anexos sin leerlo, copiarlo, grabarlo, distribuirlo o divulgarlo o hacer cualquier otro uso de la información sin el consentimiento de la empresa. El correo electrónico vía Internet no permite asegurar la confidencialidad o correcta recepción de los mensajes, por lo que la Empresa no asume responsabilidad alguna por los daños causados. Sus datos personales serán tratados por empresas del Grupo SEIDOR. para responder a sus consultas. De acuerdo con el artículo 6.1.f del RGPD, la base jurídica del tratamiento de datos personales es la operación y gestión de los servicios y actividades propias del negocio de las empresas del Grupo SEIDOR. Sus datos no se cederán a terceros, salvo obligación legal. Puede ejercer sus derechos en materia de protección de datos (acceder, rectificar y suprimir sus datos, entre otros) enviando un e-mail a ***@***.*** Puede conocer nuestra política de privacidad en mayor detalle aqui.<http://www.seidor.es/content/seidorweb/es/politica.html>.

The information contained in this communication is confidential, may be privileged and is intended for the exclusive use of the above named addressee. If you receive this communication in error, please notify the sender immediately and delete it, and all its attached documents. If you are not the intended recipient, you are expressly prohibited from reading, copying, distributing, disseminating or, in any other way, using any of the information without the company consent. Please note that Internet e-mail guarantees neither the confidentiality nor the proper receipt of the message sent, so that the Company shall not be liable for any damages caused. Your personal data will be processed by our Group Companies to answer your queries. According to article 6.1.f of the GDPR, the legal basis for the personal data processing is the operation and management of the services and activities inherent to the business of the SEIDOR Group´s companies. Your data will not be transferred to third parties, except legal obligation. You can exercise your rights in terms of data protection (access, rectification and cancellation of your data, among others) by sending an e-mail to the following address ***@***.*** To learn more about our privacy policy, click Here.<http://www.seidor.es/content/seidorweb/en/politica.html>

________________________________
De: Colin Longman ***@***.***>
Enviado: jueves, 10 de febrero de 2022 2:07
Para: MicrosoftDocs/OfficeDocs-SkypeForBusiness
Cc: Nicolás Woycik; Mention
Asunto: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Missing terms definition (#7767)


Hi @nwoycik<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnwoycik&data=04%7C01%7Cnicolas.woycik%40seidor.com%7C37f90aa0935747cbbc3708d9ec31b8cb%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637800520568810297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M9F9%2B6S2%2FHO2ccQtUtmR4i9XqUDtAccVabF%2FeMIqtEE%3D&reserved=0>

The AACallFlow field reports on the various stages of a call as it makes its way through an auto attendant. Depening on your AA configuration you may not see all of the values show. Here, at a high level, is what they mean:

§ abs_search: - directory search - dial by name
§ announcement: - an announcement was played via the AA menu option Announcement feature
§ automatic_menu: - unknown - I will look into this one further
§ call_termination: AA terminated the call - see AACallResult for more information
§ call_transfer: AA transferred the call - see AACallResult and AATransferAction for more information
§ first_level_menu: Menu option is enabled and menu was played
§ main_menu: call entered the AA / was returned to the start of the AA (ex. from an announcement)
§ speech_input_confirmation: - unknown - I will look into this one further
§ user_selection: directory search - dial by name - when a user from a list is selected (believe this is the case - waiting for data confirmation)

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F7767%23issuecomment-1034376670&data=04%7C01%7Cnicolas.woycik%40seidor.com%7C37f90aa0935747cbbc3708d9ec31b8cb%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637800520568810297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YoSL5nD7WByAxo4AAzvLFvkwcJd536iefZ%2Bv76YreWE%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXV2YLAND65FDXIGXUCPXOTU2MFVLANCNFSM5DE236AA&data=04%7C01%7Cnicolas.woycik%40seidor.com%7C37f90aa0935747cbbc3708d9ec31b8cb%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637800520568966554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kpcuQQafpjFNLTuvgJEtBEZoWYZ3QttDgFNSl%2FyPH1I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnicolas.woycik%40seidor.com%7C37f90aa0935747cbbc3708d9ec31b8cb%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637800520568966554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yUaquu9n7l3o90rvfh4i2vYhDaj%2FvbuD9gnTdVmosz0%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnicolas.woycik%40seidor.com%7C37f90aa0935747cbbc3708d9ec31b8cb%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637800520568966554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DwIqgBXNhIQm8QGjHTl9CezbaPM1YtjFVoXMfSzNSmg%3D&reserved=0>.
