### ISSUE TITLE
Error in page https://learn.microsoft.com/en-us/microsoftteams/rooms/recovery-tool

### ISSUE THREAD

**Issue by docpauluk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9663]
[Enter feedback here]
Under the heading "Running the tool", point 5 is inside the Warning section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13376c1b-df70-83de-8e6a-8ddc940774b5
* Version Independent ID: 6a2531ee-ac88-ee83-b858-1928d6cb4c65
* Content: [Use the Microsoft Teams Rooms recovery tool - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/recovery-tool)
* Content Source: [Teams/rooms/recovery-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/recovery-tool.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by docpauluk** [comment]
Nope, the issue still exists:

Step 5 is still inside the Warning section:

[image: image.png]
