### ISSUE TITLE
The example given in the Remove a policy from a group section is not clear

### ISSUE THREAD

**Issue by rabindra-harlalka** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9845]
In the "Remove a policy from a group" section, the illustration given with the help of tables doesn't seem to match with the description of the example. The description says:
> When you remove a policy from a group, the priorities of other policies of the same type assigned to that group, and that have a lower ranking, are updated.

However, the example in the table shows the scenario where policies of the same type are assigned to different groups.

So, the example is not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 888fe05b-1160-452f-90ba-deb19adb740f
* Version Independent ID: 4091c5e4-7a90-7fe4-2741-16bbb1f297c1
* Content: [Assign policies to users and groups - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/assign-policies-users-and-groups#assign-a-policy-to-a-group)
* Content Source: [Teams/assign-policies-users-and-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/assign-policies-users-and-groups.md)
* Service: **msteams**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by rabindra-harlalka** [comment]
@dariomws , I can see that you have made changes in #9889 as per the feedback. However, I have a doubt the capability described. Not sure about other policy types but for `TeamsComplianceRecordingPolicy` type, when I try assigning more than one policy of this type to the same group, I see the following error:
`Cannot assign another policy of type TeamsComplianceRecordingPolicy to the same group.`

If this is true, and I am not doing something wrong, then the example is not even possible. In this case, the only valid example would be policy assigned to multiple groups, and which would match the table present originally.
Could you please confirm if the above error is expected?

**Comment by dariomws** [comment]
Hi @rabindra-harlalka, thank you for letting me know about my error. I have tested it and the example/table looks good:
![image](https://user-images.githubusercontent.com/33589238/229093024-c8def6cf-7dcf-4941-ae1f-74708d6f6d22.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by rabindra-harlalka** [comment]
@dariomws , the table is fine then. The issue remaining still is that the "the priorities of other policies of the same type assigned to that group, and that have a lower ranking, are updated" phrase is misleading for two reason: 1) it doesn't match with the example in the table, 2) it implies that assigning multiple policies of the same type to the same group is possible, but which is at least not true for TeamsComplianceRecordingPolicy type.

**Comment by scanum** [comment]
@dariomws
